version: '2'
services:
  db_test:
    image: postgres:11.10
  web_test:
    build: .
    entrypoint: ./entry.sh
    ports:
      - "3030-3050:3030-3050"
    expose:
      - 3030-3050
    environment:
      - RSPEC_PATTERN="spec/integration/utf8_exercise_spec.rb"
      - DB_HOST=db_test
      - HOST=$HOST
      - SANDBOX_URL=$SANDBOX_URL
      - SANDBOX_HOST=http://10.8.0.100
      - SANDBOX_PORT=57001
      - REPORT_URL=$REPORT_URL
      - REPORT_PORT=4567
      - RAILS_ENV=test
      - RACK_ENV=test
      - MULTI_HOST_SETUP=1
    depends_on:
      - db_test
    volumes:
      - .:/app
