version: '2'
services:
  db_dev:
    image: postgres:11.10
    volumes:
      - ./pg-data:/var/lib/postgresql
  web_dev:
    build: .
    entrypoint: ./dev-entry.sh
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db_dev
      - HOST=$HOST
      - SANDBOX_URL=$SANDBOX_URL
    depends_on:
      - db_dev
