version: '2'
services:
  sandbox:
    image: testmycode/tmc-sandbox:0.0.3
    expose:
      - 3001
    volumes:
      - /tmp:/dev/shm
  db:
    image: postgres:11.10
    volumes:
      - ./pg-data:/var/lib/postgresql
  dev:
    build: .
    entrypoint: ./dev-entry.sh
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - HOST=dev
      - SANDBOX_URL=http://sandbox:3001
    depends_on:
      - db
      - sandbox
